<?php
/**
 * # ----
 * #     Yprisoner <yyprisoner@gmail.com>
 * #                   2019/9/23 20:56
 * #                            ------
 **/

namespace YsOpen\Tests;

class TestCase extends \PHPUnit\Framework\TestCase {
    //
    protected function setUp(): void {
        require_once __DIR__ . '/../vendor/autoload.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}