<?php
/**
 * ##################################################################################################
 * # ------------Oooo---
 * # -----------(----)---
 * # ------------)--/----
 * # ------------(_/-
 * # ----oooO----
 * # ----(---)----
 * # -----\--(--
 * # ------\_)-
 * # ----
 * #     Yprisoner <yyprisoner@gmail.com>
 * #
 * #                            ------
 * #    「 涙の雨が頬をたたくたびに美しく 」
 * ##################################################################################################
 */

namespace YsOpen\Tests;

class TestCase extends \PHPUnit\Framework\TestCase
{
    //
    protected function setUp(): void
    {
        require_once __DIR__ . '/../vendor/autoload.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
